# Generated by Django 2.1.3 on 2018-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
